# Generated by Django 6.1 on 2026-08-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad de residencia para escalabilidad de búsqueda', max_length=100, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento de residencia para escalabilidad de búsqueda', max_length=100, verbose_name='departamento'),
        ),
    ]
