# Generated by Django 6.1 on 2026-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_departamento_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='foto de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, help_text='Banner superior del perfil personal', null=True, upload_to='covers/', verbose_name='imagen de portada'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Enlace externo (portafolio, redes, etc.)', verbose_name='sitio web'),
        ),
    ]
