# Generated by Django 6.1 on 2026-08-30 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Retrato', 'Retrato'), ('Editorial', 'Editorial'), ('Eventos', 'Eventos'), ('Moda', 'Moda'), ('Arquitectura', 'Arquitectura')], default='Retrato', max_length=50)),
                ('media_type', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('video_url', models.URLField(blank=True)),
                ('equipment', models.CharField(blank=True, max_length=200)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
                'ordering': ['-created_at'],
            },
        ),
    ]
