# Generated by Django 6.1 on 2026-08-30 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(help_text='Valor total fijado por fotógrafo')),
                ('platform_fee', models.PositiveIntegerField(default=0)),
                ('artist_payout', models.PositiveIntegerField(default=0)),
                ('base_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Confirmada'), ('rejected', 'Rechazada'), ('completed', 'Finalizada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
